### PR TITLE
#25 Movie Time Skill

### PR DESCRIPTION
**Pull request by Kathuria**
Added movie time skill

# Description
Want to watch a movie now but don't know what's a good choice? Use Movie Time! This skill gives you a good movie recommendation.

Updates #25 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by garimasingh128** [comment]
Mention the issue and change folder name to MOVIE_TIME_SKILL

**Comment by Kathuria** [comment]
Done

**Comment by garimasingh128** [comment]
Good work!

**Comment by Kathuria** [comment]
Thanks @garimasingh128 . Can we close issue #25

**Comment by garimasingh128** [comment]
Let it be open. 2 same skills can have different implementations.

**Pull request merged**
