### PR TITLE
Updated Contributing.md

### LINKED ISSUE #11: Add contributing guidelines
See #2  for reference
add points from https://github.com/garimasingh128/gitsetgo

### PR DESCRIPTION
**Pull request by codeshruti**
# Description
Updated Contributing Guidelines

Fixes #11 

## Type of change

- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by garimasingh128** [comment]
Mention issue number!

**Comment by codeshruti** [comment]
Have added the issue number.

**Review by garimasingh128 — CHANGES_REQUESTED** [review]
I would also like you to add points form issue https://github.com/garimasingh128/Alexa-skills-starters/issues/2 in this such as how to go to Alexa dev console and how to download your skill under a separate heading in a proper bullet points manner. Rest all looks good.

**Comment by codeshruti** [comment]
Have done the required changes.

**Pull request merged**
